(begin (print (equal? '(1 (2 "three" #(5 (6 seven))))
                      '(1 (2 "three" #(5 (6 seven))))))
       (print (equal? '(1 (2 "three" #(5 (6 seven "eight"))))
                      '(1 (2 "three" #(5 (6 "eight"))))))
       (print (equal? '(1 (2 "three" #(5 (6 seven))))
                      '(1 (2 "three" #(5 (6 "eight"))))))
       (print (= 90 90)))
