(let ((k (let/cc k k)))
;    (print (pickle (unmemoize k))))
    (print k)
    (if (procedure? k)
        (begin (write (unmemoize k)) (newline)
               (transfer (memoize (unmemoize k)) 91)
               (print "one")
               (k 90)
               (print "two"))))
