(let loop ((i 0))
    (define (up v)
        (print v)
        (loop (+ i 1)))
    ;`(body (form (a (@ (href ,(save up))) "up")))
    ;`(body form ,i " " a (@ href ,up) "up")
    (let* ((url (get-config "url"))
           (action (if url `(action ,url) '())))
        `(body form (@ ,@action method "post") ,i " "
            (input (@ type "hidden" name "state" value ,up))
            (input (@ type "submit" name "direction" value "Up"))
            input (@ type "submit" name "direction" value "Down"))
    ))
