(let ((prev-stats '()) (i 0))
    (set-gc-callback! (lambda (stats)
        (print stats)
        (set! i (+ i 1))
        (if (vector? stats)
            (if (or (< i 3)
                    (equal? (vector-ref stats 2) (vector-ref prev-stats 2)))
                (set! prev-stats stats)
                #f)
            (if (= i 1)
                (set! prev-stats stats)
                (< (abs (- stats prev-stats)) 1000)))))
    (let loop ()
        (let ((p (cons 1 2)))
            (set-cdr! p p)
            (loop))))
