(let ((prev-stats '()) (i 0))
    (set-gc-callback! (lambda (stats)
        (print stats)
        (set! i (+ i 1))
        (if (= (length stats) 1)
            (print "HELLO")
            (if (or (< i 3)
                    (equal? (vector-ref stats 2) (vector-ref prev-stats 2)))
                (set! prev-stats stats)
                #f))))
    (let loop ()
        (let ((p (cons 1 2)))
            (set-cdr! p p)
            (loop))))
